name: Main docker build

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'src/**'
      - 'Dockerfile'
      - 'entrypoint.sh'
      - 'package.json'
      - 'package-lock.json'

env:
  REGISTRY: ghcr.io
  GH_REPO: ${{ github.repository }}
  IMAGE_VERSION: "1.0.1"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Repository name to lowercase
      run: |
          echo "IMAGE_NAME=${GH_REPO,,}" >>${GITHUB_ENV}

    - name: login
      uses: docker/login-action@v1
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

    - name: build-push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags:
          - "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v${{ env.IMAGE_VERSION }}"
          - "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
          - "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main"